import { render, screen, waitFor } from '@testing-library/react'
import userEvent from '@testing-library/user-event'
import { afterEach, describe, expect, it } from 'vitest'
import App, { formatGunLocation } from './App'

afterEach(() => window.sessionStorage.clear())

describe('armory workflow', () => {
  it('labels stored guns without a safe or slot as unassigned', () => {
    expect(formatGunLocation({ status: 'Stored' } as Parameters<typeof formatGunLocation>[0])).toBe('Location unassigned')
    expect(formatGunLocation({ status: 'Stored', reportedSafe: 7 } as Parameters<typeof formatGunLocation>[0])).toBe('Safe 7 · Slot unknown')
  })

  it('restores the last main navigation page after a reload', async () => {
    const user = userEvent.setup()
    const firstRender = render(<App />)

    await user.click(await screen.findByRole('button', { name: /audits/i }))
    expect(await screen.findByRole('heading', { name: /^audits$/i })).toBeInTheDocument()

    firstRender.unmount()
    render(<App />)

    expect(await screen.findByRole('heading', { name: /^audits$/i })).toBeInTheDocument()
  })

  it('derives inventory totals from loaded guns and applies register filters', async () => {
    const user = userEvent.setup()
    render(<App />)
    expect(await screen.findByText('Total active guns')).toBeInTheDocument()
    expect(screen.getByText('Showing active inventory · 5 guns loaded')).toBeInTheDocument()
    const sidebar = document.querySelector('.sidebar') as HTMLElement
    expect(getComputedStyle(sidebar).height).toBe('100vh')
    expect(getComputedStyle(sidebar).position).toBe('sticky')
    expect((await screen.findAllByText('Demo account')).length).toBeGreaterThanOrEqual(2)
    expect(screen.queryByText("Morgan O'Neill")).not.toBeInTheDocument()
    expect(screen.getByRole('banner')).toHaveTextContent('Demo account')
    expect(screen.getByRole('banner')).toHaveTextContent('Account administrator')
    expect(screen.getByText('USMA SKEET & TRAP')).toBeInTheDocument()
    expect(screen.queryByText('WEST POINT')).not.toBeInTheDocument()
    expect(screen.queryByText('Current workspace')).not.toBeInTheDocument()
    expect(document.querySelector('.workspace-switcher')).toBeNull()
    expect(document.querySelectorAll('.gun-thumb')).toHaveLength(0)
    expect(screen.getByRole('group', { name: /assignment filters/i })).toBeInTheDocument()
    expect(screen.getByRole('group', { name: /owner filters/i })).toBeInTheDocument()
    const totalCard = screen.getByRole('button', { name: 'Show all active guns' })
    await user.click(screen.getByRole('button', { name: 'Show checked out guns' }))
    expect(screen.getByText('Showing 1 of 5 guns')).toBeInTheDocument()
    expect(totalCard).not.toHaveClass('selected')
    expect(totalCard).not.toHaveClass('stat-card-primary')
    expect(screen.getByText('WP-24-00204')).toBeInTheDocument()
    expect(screen.queryByText('WP-24-00187')).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Show checked out guns', pressed: true })).toBeInTheDocument()
  })

  it('combines owner and inventory filters', async () => {
    const user = userEvent.setup()
    render(<App />)
    await screen.findByText('WP-24-00187')
    await user.click(screen.getByRole('button', { name: 'Personal', pressed: false }))
    await user.click(screen.getByRole('button', { name: 'Show stored guns' }))
    expect(screen.getByText('WP-22-00106')).toBeInTheDocument()
    expect(screen.queryByText('WP-24-00187')).not.toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Personal', pressed: true })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: 'Show stored guns', pressed: true })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Show all active guns' }))
    await user.click(screen.getByRole('button', { name: 'DCA', pressed: false }))
    expect(screen.getByText('WP-23-00091')).toBeInTheDocument()
  })

  it('shows live safe counts and composes location filters with assignment', async () => {
    const user = userEvent.setup()
    render(<App />)
    expect(await screen.findByRole('region', { name: /storage location overview/i })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /filter inventory to safe 7, 1 guns/i })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /filter inventory to unlocated or off-site guns, 2 guns/i })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /filter inventory to safe 7, 1 guns/i }))
    expect(screen.getByText('WP-22-00106')).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Show all active guns' }))
    await user.click(screen.getByRole('button', { name: /filter inventory to safe 6, 1 guns/i }))
    await user.click(screen.getByRole('button', { name: 'Unassigned', pressed: false }))
    expect(screen.getByText('WP-24-00312')).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /filter inventory to safe 6, 1 guns/i, pressed: true })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /filter inventory to unlocated or off-site guns, 2 guns/i }))
    await user.click(screen.getByRole('button', { name: 'Assigned', pressed: false }))
    expect(screen.getByText('WP-24-00204')).toBeInTheDocument()
    expect(screen.queryByText('WP-24-00312')).not.toBeInTheDocument()
  })

  it('composes unassigned filters with register sorting and opens gun details', async () => {
    const user = userEvent.setup()
    render(<App />)
    await screen.findByText('WP-24-00312')
    await user.click(screen.getByRole('button', { name: 'Unassigned', pressed: false }))
    expect(screen.getByText('WP-24-00312')).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /serial number, sorted ascending/i }))
    await user.click(screen.getByRole('button', { name: /open wp-24-00312/i }))
    expect(await screen.findByRole('complementary', { name: /details for wp-24-00312/i })).toHaveTextContent('Safe 6 · Slot 21')
    await user.click(screen.getByRole('button', { name: /^History/i }))
    expect((await screen.findAllByText('Location updated')).length).toBeGreaterThan(0)
    expect(screen.getByRole('button', { name: /^History/i })).toHaveTextContent('3')
  })

  it('filters assignable Beretta guns and assigns a fitted gun to an available slot', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: 'Gun Fitter' }))
    expect(await screen.findByRole('heading', { name: 'Gun Fitter' })).toBeInTheDocument()
    expect(screen.getByText('WP-24-00312')).toBeInTheDocument()
    expect(screen.queryByText('WP-24-00187')).not.toBeInTheDocument()

    await user.type(screen.getByRole('spinbutton', { name: 'Minimum length of pull' }), '14.5')
    expect(await screen.findByText('No assignable guns match these filters.')).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: 'Reset' }))
    expect(await screen.findByText('WP-24-00312')).toBeInTheDocument()

    await user.click(screen.getByRole('button', { name: 'Assign WP-24-00312' }))
    expect(await screen.findByRole('dialog', { name: /assign fitted gun/i })).toBeInTheDocument()
    const safe = screen.getByRole('combobox', { name: 'Safe' })
    const slot = screen.getByRole('combobox', { name: 'Slot' })
    expect(Array.from(slot.querySelectorAll('option')).map((option) => option.value)).toContain('21')
    await user.selectOptions(safe, '6')
    await user.selectOptions(slot, '22')
    await user.type(screen.getByRole('textbox', { name: 'Cadet shooter' }), 'R. Fitter')
    await user.click(screen.getByRole('button', { name: 'Assign gun' }))
    expect(await screen.findByText('No assignable guns match these filters.')).toBeInTheDocument()
  })

  it('separates the two specifications columns in the gun drawer', async () => {
    const user = userEvent.setup()
    render(<App />)
    await screen.findByText('WP-24-00187')

    await user.click(screen.getByRole('button', { name: /open WP-24-00187/i }))

    expect(getComputedStyle(document.querySelector('.spec-grid') as HTMLElement).columnGap).toBe('24px')
  })

  it('puts the scan-first audit flow behind one dominant action', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: /start monthly audit/i }))
    expect(screen.getByRole('heading', { name: /start an audit/i })).toBeInTheDocument()
    const name = screen.getByRole('textbox', { name: /audit name/i })
    await user.type(name, 'August 2026 monthly inventory scan')
    await user.click(screen.getByRole('button', { name: /^start audit$/i }))
    expect(await screen.findByRole('heading', { name: /august 2026 monthly inventory scan/i })).toBeInTheDocument()
    const scan = screen.getByRole('textbox', { name: /scan qr code/i })
    await user.type(scan, 'WP-24-00187')
    await user.click(screen.getByRole('button', { name: /^scan$/i }))
    await waitFor(() => expect(screen.getByText(/verified in current inventory/i)).toBeInTheDocument())
    expect(screen.getByText('WP-24-00187')).toBeInTheDocument()
    for (const nextSerial of ['WP-24-00204', 'WP-23-00091', 'WP-24-00312', 'WP-22-00106']) {
      await user.type(scan, nextSerial)
      await user.click(screen.getByRole('button', { name: /^scan$/i }))
      await waitFor(() => expect(screen.getByText(new RegExp(`${nextSerial} verified in current inventory`, 'i'))).toBeInTheDocument())
    }
    expect(screen.getByText('Scanned guns')).toBeInTheDocument()
    expect(screen.getAllByText('5 scanned').length).toBeGreaterThanOrEqual(1)
    for (const scannedSerial of ['WP-24-00187', 'WP-24-00204', 'WP-23-00091', 'WP-24-00312', 'WP-22-00106']) {
      expect(screen.getAllByText(scannedSerial).length).toBeGreaterThan(0)
    }
    await user.click(screen.getByRole('button', { name: /^scan$/i }))
    expect(screen.getByText(/scan or enter a serial number/i)).toBeInTheDocument()
    await user.type(scan, 'WP-24-00187')
    await user.click(screen.getByRole('button', { name: /^scan$/i }))
    expect(await screen.findByText(/already scanned in this audit/i)).toBeInTheDocument()
  })

  it('presents the audit status filter as an accessible, focused control', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: /audits/i }))
    expect(await screen.findByRole('heading', { name: /^audits$/i })).toBeInTheDocument()
    expect(screen.getByText('Filter by status')).toBeInTheDocument()
    const status = screen.getByRole('combobox', { name: 'Audit status' })
    expect(status).toHaveClass('audit-status-filter-select')
    await user.selectOptions(status, 'Complete')
    expect(screen.getByText(/no audits match this filter/i)).toBeInTheDocument()
  })

  it('assigns or reassigns a cadet from the gun drawer', async () => {
    const user = userEvent.setup()
    render(<App />)
    await screen.findByText('WP-24-00187')
    await user.click(screen.getByRole('button', { name: /open WP-24-00187/i }))
    await user.click(screen.getByRole('button', { name: /reassign/i }))
    const cadet = screen.getByRole('textbox', { name: /cadet shooter/i })
    await user.clear(cadet)
    await user.type(cadet, 'R. Test')
    await user.click(screen.getByRole('button', { name: /save change/i }))
    expect((await screen.findAllByText('R. Test')).length).toBeGreaterThanOrEqual(1)
    await user.click(screen.getByRole('button', { name: /^unassign$/i }))
    expect(await screen.findByRole('heading', { name: /remove cadet assignment/i })).toBeInTheDocument()
    expect(screen.getByRole('button', { name: /^unassign gun$/i })).toBeDisabled()
    await user.click(screen.getByRole('checkbox', { name: /ends the active assignment/i }))
    await user.click(screen.getByRole('button', { name: /^unassign gun$/i }))
    expect((await screen.findAllByText('Unassigned')).length).toBeGreaterThanOrEqual(1)
  })

  it('sorts the register and checks a gun back into a safe', async () => {
    const user = userEvent.setup()
    render(<App />)
    await screen.findByText('WP-24-00204')
    await user.click(screen.getByRole('button', { name: /serial number, sorted ascending/i }))
    const rows = screen.getAllByRole('button', { name: /open WP-/i })
    expect(rows[0]).toHaveAccessibleName(/open WP-24-00312/i)
    await user.click(screen.getByRole('button', { name: /open WP-24-00204/i }))
    expect(await screen.findByRole('complementary', { name: /details for WP-24-00204/i })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /check in/i }))
    await user.click(screen.getByRole('button', { name: /save change/i }))
    expect((await screen.findAllByText('Safe 2 · Slot 1')).length).toBeGreaterThanOrEqual(1)
  })

  it('edits descriptive gun details while retaining the serial and location', async () => {
    const user = userEvent.setup()
    render(<App />)
    await screen.findByText('WP-24-00187')
    await user.click(screen.getByRole('button', { name: /open WP-24-00187/i }))
    await user.click(screen.getByRole('button', { name: /edit details/i }))
    const model = screen.getByRole('textbox', { name: 'Model' })
    await user.clear(model)
    await user.type(model, 'Beretta 694')
    const owner = screen.getByRole('textbox', { name: /owner \/ manufacturer/i })
    await user.clear(owner)
    await user.type(owner, 'DCA')
    await user.selectOptions(screen.getByRole('combobox', { name: 'High-rib' }), 'yes')
    await user.click(screen.getByRole('button', { name: /save change/i }))
    expect(await screen.findByText('Beretta 694 · 12 ga')).toBeInTheDocument()
    expect(screen.getAllByText('Safe 3 · Slot 8').length).toBeGreaterThan(0)
    await user.click(screen.getByRole('button', { name: /^History/i }))
    expect(await screen.findByText(/Updated model, owner, length of pull, high-rib/i)).toBeInTheDocument()
  })

  it('only offers exceptions for an actual unresolved audit item', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: /start monthly audit/i }))
    await user.type(screen.getByRole('textbox', { name: /audit name/i }), 'Exception test audit')
    await user.click(screen.getByRole('button', { name: /^start audit$/i }))
    expect(await screen.findByRole('heading', { name: /exception test audit/i })).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /exceptions/i }))
    const select = screen.getByRole('combobox', { name: /unresolved gun/i })
    await user.selectOptions(select, 'WP-24-00204')
    expect(await screen.findByRole('heading', { name: /resolve as an exception/i })).toBeInTheDocument()
    expect(screen.queryByText('Choose a reason for this unresolved gun.')).not.toBeInTheDocument()
  })

  it('hydrates a reopened audit so persisted scans and exceptions remain available', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: /start monthly audit/i }))
    await user.type(screen.getByRole('textbox', { name: /audit name/i }), 'Reopen audit test')
    await user.click(screen.getByRole('button', { name: /^start audit$/i }))
    const scan = await screen.findByRole('textbox', { name: /scan qr code/i })
    await user.type(scan, 'WP-24-00187')
    await user.click(screen.getByRole('button', { name: /^scan$/i }))
    await screen.findByText(/wp-24-00187 verified in current inventory/i)

    await user.click(screen.getByRole('button', { name: /all audits/i }))
    await user.click(screen.getByRole('button', { name: /^audits$/i }))
    await user.click(await screen.findByRole('button', { name: /reopen audit test/i }))

    expect(await screen.findByText('WP-24-00187')).toBeInTheDocument()
    const exceptions = screen.getByRole('button', { name: /exceptions/i })
    expect(exceptions).toBeEnabled()
    await user.click(exceptions)
    expect(screen.getByRole('combobox', { name: /unresolved gun/i })).toBeInTheDocument()
  })

  it('enables PDF reconciliation after the physical count is finalized', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: /start monthly audit/i }))
    await user.type(screen.getByRole('textbox', { name: /audit name/i }), 'PDF reconciliation test')
    await user.click(screen.getByRole('button', { name: /^start audit$/i }))
    const scan = await screen.findByRole('textbox', { name: /scan qr code/i })
    for (const serial of ['WP-24-00187', 'WP-24-00204', 'WP-23-00091', 'WP-24-00312', 'WP-22-00106']) {
      await user.type(scan, serial)
      await user.click(screen.getByRole('button', { name: /^scan$/i }))
      await screen.findByText(new RegExp(`${serial} verified in current inventory`, 'i'))
    }
    await user.click(screen.getByRole('button', { name: /finalize physical count/i }))
    const upload = await screen.findByLabelText(/upload pdf report/i)
    await waitFor(() => expect(upload).toBeEnabled())
    await user.upload(upload, new File(['test PDF'], 'monitoring-report.pdf', { type: 'application/pdf' }))
    expect(await screen.findByRole('textbox', { name: /reviewed serial numbers/i })).toBeInTheDocument()
  })

  it('archives a gun with a justification and exposes it in the dedicated archived area', async () => {
    const user = userEvent.setup()
    render(<App />)
    await screen.findByText('WP-24-00187')
    await user.click(screen.getByRole('button', { name: /open WP-24-00187/i }))
    await user.click(screen.getByRole('button', { name: /archive gun/i }))
    expect(await screen.findByRole('heading', { name: /archive gun/i })).toBeInTheDocument()
    const archiveConfirm = screen.getAllByRole('button', { name: /^archive gun$/i }).find((button) => button.classList.contains('button-primary'))!
    expect(archiveConfirm).toBeDisabled()
    await user.type(screen.getByRole('textbox', { name: /justification/i }), 'Retired after documented damage')
    await user.click(screen.getByRole('checkbox', { name: /removes the gun from active inventory/i }))
    await user.click(screen.getAllByRole('button', { name: /^archive gun$/i }).find((button) => button.classList.contains('button-primary'))!)
    expect(await screen.findByText('Archived')).toBeInTheDocument()
    await user.click(screen.getByRole('button', { name: /archived guns/i }))
    expect(await screen.findByRole('heading', { name: /archived guns/i })).toBeInTheDocument()
    expect((await screen.findAllByText('WP-24-00187')).length).toBeGreaterThanOrEqual(2)
  })

  it('shows searchable global activity and opens a related gun from its serial', async () => {
    const user = userEvent.setup()
    render(<App />)
    await user.click(screen.getByRole('button', { name: /activity history/i }))
    expect(await screen.findByRole('heading', { name: /activity history/i })).toBeInTheDocument()
    expect((await screen.findAllByText('Location updated')).length).toBeGreaterThan(0)
    const search = screen.getByRole('textbox', { name: /search activity/i })
    await user.clear(search)
    await user.type(search, 'WP-24-00312')
    expect((await screen.findAllByText('WP-24-00312')).length).toBeGreaterThan(0)
    await user.click(screen.getAllByRole('button', { name: 'WP-24-00312' })[0])
    expect(await screen.findByRole('complementary', { name: /details for wp-24-00312/i })).toBeInTheDocument()
  })
})
